export default function About() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 relative overflow-hidden">
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-20 left-10 w-72 h-72 bg-orange-500/10 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-20 right-10 w-96 h-96 bg-red-500/10 rounded-full blur-3xl animate-pulse delay-1000"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-80 h-80 bg-yellow-500/5 rounded-full blur-3xl animate-pulse delay-500"></div>
      </div>

      <div className="relative z-10 container mx-auto px-4 py-8 max-w-5xl sm:px-6 lg:px-8 mt-9">
        <div className="bg-slate-800/80 backdrop-blur-sm rounded-lg shadow-2xl p-6 sm:p-8 border border-orange-500/20">
          <h1 className="text-3xl sm:text-4xl font-bold bg-gradient-to-r from-orange-400 via-red-500 to-yellow-500 bg-clip-text text-transparent mb-4 sm:mb-6">About AI Roast Machine</h1>
          
          <div className="prose prose-lg max-w-none">
            <p className="text-slate-300 mb-4 text-lg sm:text-xl leading-relaxed">
              Welcome to the AI Roast Machine - where artificial intelligence meets comedy! 
              Our advanced AI has been trained on thousands of jokes, roasts, and witty comebacks 
              to deliver personalized roasts that are both hilarious and surprisingly clever.
            </p>
            
            <h2 className="text-xl sm:text-2xl font-semibold text-orange-300 mt-4 sm:mt-6 mb-3 sm:mb-4">How it works:</h2>
            <ul className="list-disc pl-5 sm:pl-6 text-slate-300 space-y-2 text-lg sm:text-xl">
              <li>Enter a name (yours or a friend's)</li>
              <li>Our AI analyzes the name and generates a custom roast</li>
              <li>Enjoy the burn! 🔥</li>
            </ul>
            
            <div className="bg-orange-600/20 border-l-4 border-orange-500 p-4 sm:p-6 mt-4 sm:mt-6 rounded-r-lg backdrop-blur-sm">
              <p className="text-orange-200 text-lg sm:text-xl">
                <strong className="text-orange-300">Disclaimer:</strong> All roasts are generated by AI and are meant for entertainment purposes only. 
                We promote good-natured fun and respect for everyone!
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}