export default function About() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-100 to-purple-100 py-8">
      <div className="container mx-auto px-4 max-w-4xl">
        <div className="bg-white rounded-lg shadow-lg p-8">
          <h1 className="text-4xl font-bold text-gray-800 mb-6">About AI Roast Machine</h1>
          
          <div className="prose prose-lg">
            <p className="text-gray-600 mb-4">
              Welcome to the AI Roast Machine - where artificial intelligence meets comedy! 
              Our advanced AI has been trained on thousands of jokes, roasts, and witty comebacks 
              to deliver personalized roasts that are both hilarious and surprisingly clever.
            </p>
            
            <h2 className="text-2xl font-semibold text-gray-800 mt-6 mb-4">How it works:</h2>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>Enter a name (yours or a friend's)</li>
              <li>Our AI analyzes the name and generates a custom roast</li>
              <li>Enjoy the burn! 🔥</li>
            </ul>
            
            <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mt-6">
              <p className="text-yellow-800">
                <strong>Disclaimer:</strong> All roasts are generated by AI and are meant for entertainment purposes only. 
                We promote good-natured fun and respect for everyone!
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
